### ISSUE TITLE
problem about fabType

### ISSUE THREAD

**Issue by fajaranugrah** [robertlevonyan/customFloatingActionButton#10]
hello guys, i got problem if first time open the activity and using app:fabMenuStyle="popUp" got like this
![device-2018-04-17-184934](https://user-images.githubusercontent.com/38461162/38865683-242c8258-4271-11e8-88f2-1adda192ac44.png)
can you help me how to fixed this
thank you

**Comment by robertlevonyan** [comment]
please check last version

**Comment by fajaranugrah** [comment]
thank you sir
