### ISSUE TITLE
cFAB icon does use scale type

### ISSUE THREAD

**Issue by inhaledesign** [robertlevonyan/customFloatingActionButton#12]
In Android's FAB, I can use android:scaleType to change how my icon is scaled to fit into the button.  This is not possible with cFAB.

**Comment by robertlevonyan** [comment]
Yes, because this FAB is inherited from TextView, so it uses TextViews compound drawables to show icons. This drawables have fixed 24dp size. 
According to Material Design specs, the FAB icon size is also should be 24dp.
