### ISSUE TITLE
Small padding in the end

### ISSUE THREAD

**Issue by CuriousNikhil** [robertlevonyan/customFloatingActionButton#25]
Why there is a small padding of around 16 dp in the end of the fab.. the view /text and icons are not aligned in center

**Comment by SasLuca** [comment]
Version 2.0.5 doesn't suffer from this issue. I went back to that version and the padding went away. I guess we have to wait for a new release for a fix.

**Comment by robertlevonyan** [comment]
check the latest version. If the problem still appears I will reopen the issue.
