### ISSUE TITLE
Floating action button does not position with Layout gravity

### ISSUE THREAD

**Issue by zia4mobileapp** [robertlevonyan/customFloatingActionButton#29]
In this example below the `fabToggle` does not move to the bottom inside the `floatLayout`.

Plus there is very limited documentation on how the toggle works. Please clarify.

Here is a screenshot, on API 19,

![robert levynon](https://user-images.githubusercontent.com/43267757/74916286-90347b80-53eb-11ea-939f-15db7c49e91d.png)

```
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    >
    <LinearLayout
        android:id="@+id/card_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
     
        >
        <com.robertlevonyan.views.customfloatingactionbutton.FloatingLayout
            android:id="@+id/floatLayout"
            android:layout_width="200dp"
            android:layout_height="200dp"
            android:layout_gravity="bottom|end"
            >

            <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
                android:id="@+id/fabToggle"
                android:layout_width="150dp"
                android:layout_height="150dp"
                android:layout_gravity="bottom"
                />
        </com.robertlevonyan.views.customfloatingactionbutton.FloatingLayout>
    </LinearLayout>
</layout>
```

**Comment by robertlevonyan** [comment]
Floating Layout must be match_parent (at least in one direction).
Use `android:gravity`istead of `android:layout_gravity`

**Comment by annng** [comment]
I try using match parent but floatingLayout doesn't want to move. It stuck on the top left. but, if I use wrap content as width and height floatingLayout, the item will offset and cropped
![image](https://user-images.githubusercontent.com/31025016/108291981-c99df380-71c5-11eb-9b9b-e90714cab01f.png)

**Comment by robertlevonyan** [comment]
please share your code

**Comment by annng** [comment]
> please share your code

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="@color/transparent"
    android:orientation="vertical"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="@dimen/margin_medium">

        <TextView
            android:id="@+id/tv_desc"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/margin_medium"
            android:text="@string/pilih_ikhwan"
            app:fontFamily="@font/proxima_nova_soft_semibold" />

        <LinearLayout
            android:id="@+id/llAction"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">




        </LinearLayout>


    </LinearLayout>


    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
            android:id="@+id/srl_pengajuan"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            android:paddingLeft="8dp"
            android:paddingRight="8dp">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_pengajuan"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:listitem="@layout/item_people"
                app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
                tools:itemCount="3" />

        </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>


        <TextView
            android:id="@+id/tvNotFound"
            android:layout_width="0dp"
            android:layout_height="@dimen/icon_medium_size"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            android:gravity="center"
            android:text="@string/label_error_no_result"
            android:textColor="@color/black"
            android:textSize="@dimen/text_medium_size"
            android:visibility="gone"
            app:fontFamily="@font/proxima_nova_soft_bold" />


        <com.robertlevonyan.views.customfloatingactionbutton.FloatingLayout
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:gravity="end|bottom"
            fab:fabColor="@color/colorPrimary"
            fab:fabType="circle"
            fab:fabMenuStyle="popUp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            >

            <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
                android:layout_width="56dp"
                android:layout_height="56dp"
                fab:fabColor="@color/white"
                android:gravity="end|bottom"
                android:layout_gravity="end|bottom"
                android:layout_margin="@dimen/margin_small"
                fab:fabIcon="@drawable/ic_filter_umur" />

            <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
                android:id="@+id/btnFilter"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                fab:fabText="@string/action_filter"
                android:layout_margin="@dimen/margin_small"
                android:gravity="end|bottom"
                fab:fabColor="@color/purple_white"
                fab:fabIcon="@drawable/ic_filter" />

            <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
                android:id="@+id/btnFavorite"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                fab:fabText="@string/action_favorit"
                android:layout_margin="@dimen/margin_small"
                android:gravity="end|bottom"
                fab:fabColor="@color/colorPrimary"
                fab:fabIcon="@drawable/ic_favorit" />

            <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
                android:id="@+id/btnCvTerkirim"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="@dimen/margin_small"
                android:gravity="end|bottom"
                fab:fabText="@string/label_cv_terkirim_value"
                fab:fabColor="@color/green"
                fab:fabIcon="@drawable/ic_terkirim" />

            <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
                android:id="@+id/btnSearch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="@dimen/margin_small"
                android:gravity="end|bottom"
                fab:fabText="@string/label_btn_search"
                fab:fabColor="@color/yellow_dark"
                fab:fabIcon="@drawable/ic_search" />


        </com.robertlevonyan.views.customfloatingactionbutton.FloatingLayout>>

    </androidx.constraintlayout.widget.ConstraintLayout>

</LinearLayout>`

**Comment by robertlevonyan** [comment]
you shouldn't use `match_parent` int `ConstraintLayout`. Set both width and height `0dp`(match_constraint), also add top constraint to `FloatingLayout`.

**Comment by annng** [comment]
> you shouldn't use `match_parent` int `ConstraintLayout`. Set both width and height `0dp`(match_constraint), also add top constraint to `FloatingLayout`.
nothing different. If I set width and height on ConstraintLayout to 0dp it will show nothing
![image](https://user-images.githubusercontent.com/31025016/108319985-cd953a00-71f4-11eb-929f-ed2a46afb054.png)

**Comment by robertlevonyan** [comment]
set the width to 0dp and constraint start. Floating layout must be full screen

**Comment by annng** [comment]
> set the width to 0dp and constraint start. Floating layout must be full screen

and how to change position FloatingLayout to end|bottom? I've try with full screen and gravity but the FloatingLayout still on top|start

**Comment by robertlevonyan** [comment]
let me check this case

**Comment by robertlevonyan** [comment]
please check the sample project. everything should be fine
