### ISSUE TITLE
Not possible to use with gradle

### ISSUE THREAD

**Issue by alm494** [robertlevonyan/customFloatingActionButton#3]
Could not determine artifacts for com.robertlevonyan.view:CustomFloatingActionButton:1.0.3
I am not behind proxy.

**Comment by robertlevonyan** [comment]
Could you write your code?

**Comment by alm494** [comment]
no code, just added this line to build.gradle:
`implementation "com.robertlevonyan.view:CustomFloatingActionButton:1.0.3"`
I also set the google support library to 26.1.0 and it resolved nice, no problems with proxy and maven repo.
` maven { url "http://jcenter.bintray.com/" }`
` maven { url "http://repo.maven.apache.org/maven2" }`
` maven { url "http://maven.google.com" }`

**Comment by robertlevonyan** [comment]
do you have google() repo in your buildscript?

**Comment by alm494** [comment]
yes, google is in repo.
may be these dependencies are the root cause?
`implementation "com.android.support:appcompat-v7:26.+"`
`implementation "com.android.support:design:26.+"`
`implementation "com.android.support:support-v4:26.+"`

**Comment by robertlevonyan** [comment]
what error it gives. I've tried it works for me

**Comment by alm494** [comment]
It just does not sync the gradle.
Android Studio 3.0.0:  start the new blanc project with min sdk 25 and add all google dependencies above. All of them will be synchronized except your package, with error messages

Error:Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.robertlevonyan.view:CustomFloatingActionButton:1.0.3
Could not get resource 'http://jcenter.bintray.com/com/robertlevonyan/view/CustomFloatingActionButton/1.0.3/CustomFloatingActionButton-1.0.3.aar'.
Could not HEAD 'http://jcenter.bintray.com/com/robertlevonyan/view/CustomFloatingActionButton/1.0.3/CustomFloatingActionButton-1.0.3.aar'.
Permission denied: connect

At the same time I can download them with browser. Again, I am not behind proxy

**Comment by robertlevonyan** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "your.package.name"
        minSdkVersion 25
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.robertlevonyan.view:CustomFloatingActionButton:1.0.3'
    testCompile 'junit:junit:4.12'
}

Here's a code I've tried. It syncs ok. Check your configurations
