### ISSUE TITLE
Custom View FAB

### ISSUE THREAD

**Issue by annng** [robertlevonyan/customFloatingActionButton#32]
is it possible to set sub button of FAB with custom view?
![image](https://user-images.githubusercontent.com/31025016/108030044-1916df00-7061-11eb-8772-276d926947df.png)

**Comment by robertlevonyan** [comment]
What do you mean?

**Comment by annng** [comment]
> What do you mean?

I look on the code that inside expand floating button have to FloatingActionButton. Can I use LinearLayout or something else to create my own Item View inside FloatingActionLayout?

**Comment by robertlevonyan** [comment]
Unfortunately not. You can use only Android's FAB or Custom FAB
