### ISSUE TITLE
Fab properties and Support Library conflict

### ISSUE THREAD

**Issue by nzeakokosi7** [robertlevonyan/customFloatingActionButton#4]
I've been trying to change the fab properties from java (programmatically) but nothing works

**Comment by robertlevonyan** [comment]
can you share your code?

**Comment by nzeakokosi7** [comment]
Unfortunately it's someone's work but
I'd give a snippet

Fab.setFabType(FloatingActionButton.FAB_TYPE_SQUARE);

**Comment by zwirne** [comment]
fab.setFabColor(R.color.event_register_button);
not working - it stays the same as defined in the xml

**Comment by robertlevonyan** [comment]
@nzeakokosi7 @zwirne can you send more details about your projects (like minApiVersion, etc.). Because it works for me

**Comment by JuanpZpp** [comment]
Hi! I'm having the same problem.

xml:

<com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
        android:id="@+id/mFabDomicilio"
        android:layout_above="@id/mCardViewTienda"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:fabSizes="mini"
        app:fabType="roundedSquare"
        android:layout_alignParentEnd="true"
        android:layout_margin="5dp"/>

code (kotlin):

mFabDomicilio.setOnClickListener {
            mFabDomicilio.fabText = "Hola"
        }

But when I click the button the text doesn't change. Here are the details:

compileSdkVersion 27
    defaultConfig {
        applicationId "com.xxx.xxxxx"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

**Comment by robertlevonyan** [comment]
Update to version 2.0.4
