### ISSUE TITLE
FAB's icon is not centered

### ISSUE THREAD

**Issue by adolgiy** [robertlevonyan/customFloatingActionButton#6]
I want to replace support FABs with cFABs, but icon is not centered :(

![image](https://user-images.githubusercontent.com/22356921/38506373-4cfedcbc-3c22-11e8-99ee-ff9b3d252877.png)

**Comment by adolgiy** [comment]
This is caused by using `wrap_content`
For now it is seen only on Nexus 6P
Also AS's preview is OK
But setting size to `56dp` fixes issue
But it is still not OK to use custom sizes :(

**Comment by robertlevonyan** [comment]
What is the parent layout?. You don't need to set a size. The Floating action button has two sizes. Normal (56dp) and small (48dp). The size you are setting will be averriten to default sizes. To have custom size use floating action layout instead

**Comment by adolgiy** [comment]
@robertlevonyan I know I don't need. But using `wrap_content` causes icon issues like on the screenshot.

**Comment by robertlevonyan** [comment]
have you added a text?

**Comment by adolgiy** [comment]
@robertlevonyan nope. the code is same to the previous issue.

**Comment by robertlevonyan** [comment]
please check the latest version, I made some changes (2.0.5)

**Comment by ash0x0** [comment]
This issue still exists in 2.0.5.
![fab](https://user-images.githubusercontent.com/12426718/41289195-47654ef4-6e49-11e8-8dc9-a1a2d92651b1.png)
Here's the layout:
```xml
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/dashboard_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment
        android:id="@+id/map"
        class="com.google.android.gms.maps.SupportMapFragment"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="1.0" />

    <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
        android:id="@+id/location_fab"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        app:fabColor="?attr/colorBackgroundFloating"
        app:fabIcon="@drawable/ic_location_fab"
        app:fabIconColor="@android:color/holo_blue_light"
        app:fabIconPosition="start"
        app:fabSizes="mini"
        app:fabType="roundedSquare"
        app:layout_constraintBottom_toTopOf="@+id/traffic_fab"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
        android:id="@+id/traffic_fab"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        app:fabColor="?attr/colorBackgroundFloating"
        app:fabIcon="@drawable/ic_traffic_fab"
        app:fabIconColor="@android:color/black"
        app:fabSizes="mini"
        app:fabType="roundedSquare"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />


</android.support.constraint.ConstraintLayout>
```
Is this something wrong with my layout?

**Comment by ash0x0** [comment]
@robertlevonyan any news on this? I've been looking at the code but I haven't been able to find anything that could be causing it. Do you have a culprit in mind?

**Comment by robertlevonyan** [comment]
Nope. But I think this issue may be caused because of Constraint layout. I've seen previously some strange behavior of other views inside it. Can you try using another parent for the CFABs?

**Comment by ash0x0** [comment]
No go. I tried relative, linear, grid and nothing worked, I even tried in a whole new project and still the same problem. Can you provide the code for the preview layouts in the readme? It works fine in the sample project but for some reason when I include it in any other project it gives me this weird result.

**Comment by mengjiin** [comment]
I encountered the same issue: 
the icon is off center with wrap_content, I specify the size to 56dp as ash0x0 mentioned, then the icon is centered OK.

**Comment by robertlevonyan** [comment]
guys check the latest version 2.1.0
