### ISSUE TITLE
Ripple effect was removed after using app:fabColor

### ISSUE THREAD

**Issue by adolgiy** [robertlevonyan/customFloatingActionButton#7]

**Comment by robertlevonyan** [comment]
Please share your code

**Comment by adolgiy** [comment]
@robertlevonyan here it is
```
        <com.robertlevonyan.views.customfloatingactionbutton.FloatingActionButton
            android:id="@+id/positiveZoom"
            android:layout_width="@dimen/fab_size"
            android:layout_height="@dimen/fab_size"
            android:layout_margin="16dp"
            app:fabColor="@color/white"
            app:fabIcon="@drawable/ic_positive_dark_24dp"
            app:fabIconColor="@color/dark"
            app:fabType="roundedSquare"
            app:layout_constraintBottom_toTopOf="@+id/negativeZoom"
            app:layout_constraintEnd_toEndOf="parent" />
```

**Comment by robertlevonyan** [comment]
The ripple is there, but the ripple color is white, and you have set white color to FAB, this is the reason why you don't see the ripple effect.

**Comment by okcoker** [comment]
@robertlevonyan any chance we can make this ripple color configurable? I also have a white button but would like to customize the ripple color.

**Comment by okcoker** [comment]
Actually I'm not seeing the ripple at all even using a different color or the default settings.

Basically using the code above without any of the `app:` settings

**Comment by robertlevonyan** [comment]
This is a good suggestion, I'll make ripple color configurable

**Comment by robertlevonyan** [comment]
@okcoker use app:fabIconColor from version 2.1.1 to customize the ripple color
