### ISSUE TITLE
Double tapping button causes open/close state to be out of sync with display

### ISSUE THREAD

**Issue by lilHermit** [robertlevonyan/customFloatingActionButton#8]
Please see gif below
![device-2018-04-11-110800](https://user-images.githubusercontent.com/299424/38610627-552b5e08-3d79-11e8-8d55-f6132403e171.gif)

As you can see although the button is in closed/collapsed state the red icon remains and opening again fixes

**Comment by robertlevonyan** [comment]
Check the new version it is fixed (2.0.5)
