### ISSUE TITLE
Can't hide/show FloatingActionButton

### ISSUE THREAD

**Issue by zhiyuanfu** [robertlevonyan/customFloatingActionButton#9]
how to hide/show FloatingActionButton?

**Comment by robertlevonyan** [comment]
please describe your problem more detailed. There are many ways to hide/show views in Android.

**Comment by alextrujillo4** [comment]
Yeah i think  @zhiyuanfu  wants to say a .show() and .hide() support with hide/show animations etc etc...

**Comment by robertlevonyan** [comment]
now you can use PropertyAnimators to hide and show FAB-s like other views.
